### ISSUE TITLE
Добавление модификатора на не корректно написанный элемент

### ISSUE THREAD

**Issue by Hurtsok** [eakoryakin/jquery-bem#1]
Начальный результат: 

``` html
<div class="b-label__elem_">Nested Element</div>
```

Добавляем модификатор 

``` js
$('.b-label__elem_').addModifier('test');
```

Результат

``` html
<div class="b-label__elem_ b-label__elem__test">Nested Block</div>
```

В результате получилось не валидное имя элемента по БЭМ методологии

**Comment by eakoriakin** [comment]
Спасибо за коммент, Hurtsok!
Проблему исправил и теперь работает следующим образом.

HTML:

``` html
<div class="b-label__elem_"></div>
```

Добавляем модификатор:

``` js
$('.b-label__elem_').addModifier('test');
```

Результат:

``` html
<div class="b-label__elem_ b-label__elem_test">Nested Block</div>
```

Модификатор "b-label__elem_test" теперь формируется правильно.
Из CSS-класса элемента "b-label__elem_" последнее нижнее подчеркивание нужно убрать вручную, потому что библиотека самостоятельно не изменяет имена элементов.
